### ISSUE TITLE
Spec Clarification: Indentation, Multistring, Multimap, and Array Syntax in bru-lang

### ISSUE THREAD

**Issue by saibotsivad** [usebruno/bru-lang#4]
Hey there, love the idea of writing this as a spec, and the spec itself is looking pretty good!

As a spec writer myself I noted a few things. Since this is a spec based on an existing implementation, I'm guessing you've already thought about these things.

Happy to hammer these out in real time (links in my profile) if that's helpful, or if you write up stuff in here I can wordsmith it into a PR. Happy to help, Bru has been a real game changer for me, so I'd love to give something back.

### Tabs versus spaces

You'll see in the Multistring section that indentation starts to matter. I admit that I'm not unbiased on this topic, but at the very least if bru-lang is picking spaces/tabs (or if it's not) it should be stated explicitly.

(When considering the issue, please consider that it's not simply "personal preference", it's actually an [accessibility issue](https://adamtuttle.codes/blog/2021/tabs-vs-spaces-its-an-accessibility-issue/).)

- [x] Clarify whether tabs versus spaces matters, and in what ways

### Multistring

In the description and examples it's unclear what this string should be interpreted as:
```
http: {
  body: {
    type: text
    data: '''
      This is a multiline string.
      It can span multiple lines.
    '''
  }
}
```
My intuitive guess is the `data` property should be `This is a multiline string.\nIt can span multiple lines.` as opposed to, for example this `\s\sThis is a multiline string.\s\sIt can span multiple lines.` or even this `\n\s\s\s\s\s\sThis is a multiline string.\n\s\s\s\s\s\sIt can span multiple lines.\n\s\s\s\s`

What should happen in this case?
```
http: {
  body: {
    type: text
    data: '''
Foo
    Bar
        Bizz
    '''
  }
}
```

Should it be `Foo\nBar\n\s\sBizz` or `Foo\n\s\s\s\sBar\n\s\s\s\s\s\s\s\sBizz` or...

- [x] Clarify whether newlines before/after are included
- [x] Clarify that the pre-spaces are removed, e.g. for indentation `n` strip up to `n + 2`

### Multimap

Mostly the edge cases here involve Multimap with unset values. Is this even allowed? E.g. what about this:
```
http: {
  query: {
    userId:
  }
}
```

My intuitive guess would be this would map to JavaScript like:
```js
const multimap = {
  http: {
    query: {
      userId: undefined
    }
  }
}
```

### Arrays

What should a Multiline look like in an array? What about a Multimap?

```
meta: {
  tags: [
    sanity
    '''
      This string
      is multiline.
    '''
    userId: 1
    regression
  ]
}
```

Presumably in this case the `tags` is equivalent to a JSON array like:
```json
[
  "sanity",
  "This string\nis multiline.",
  { "userId": 1 },
  "regression"
]
```

This should probably just be an example added, to be explicit.

**Comment by helloanoop** [comment]
Hey @saibotsivad 

We have a call today - 24 Jan 2023 at GMT 5pm on Discord. It's be awesome if you could join it

https://discord.com/invite/xEw7K3BM?event=1199350756269101167

**Comment by halostatue** [comment]
I believe that most of your questions are addressed in the [spec](https://github.com/brulang/bru-lang/blob/main/bru-spec-v1.md#multistring).

> ### Tabs versus spaces
> You'll see in the Multistring section that indentation starts to matter. I admit that I'm not unbiased on this topic, but at the very least if bru-lang is picking spaces/tabs (or if it's not) it should be stated explicitly.

We do specify that indentation levels are two spaces:

```markdown
Bru is block-oriented and uses both delimiters and indentation to ensure correctness.
When a new block context is started, the contents of the block MUST be indented to
the next level. Each level of indentation in Bru is signified with two ASCII space
characters (0x20).
```

Tabs are not supported for indentation, but will be preserved within strings or multistrings.

> ### Multistring

> In the description and examples it's unclear what this string should be interpreted as:

I have tried to provide multiple [explicit examples](https://github.com/brulang/bru-lang/blob/main/bru-spec-v1.md#multistring) for this to reduce this question. If you have some suggestions on how to clarify these examples further, I would appreciate them.

> ```
> http: {
>   body: {
>     type: text
>     data: '''
> Foo
>     Bar
>         Bizz
>     '''
>   }
> }
> ```

This should not parse. The `n + 2` indentation is required for multiline strings.

> ### Multimap
> Mostly the edge cases here involve Multimap with unset values. Is this even allowed? E.g. what about this:
> 
> ```
> http: {
>   query: {
>     userId:
>   }
> }
> ```

This would be the equivalent of `{ "http": { "query": { "userId": "" } } }`.

> ### Arrays
> What should a Multiline look like in an array? What about a Multimap?

There are examples for this in the specification.

**Comment by saibotsivad** [comment]
Excellent answer and response, thank you so much for your time!
